name: Clean Up Untagged Images

on:
  schedule:
    - cron: 0 0 * * 0 # run at midnight every sunday
  workflow_dispatch:

jobs:
  clean_up_untagged_images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
